/*
Copyright © 2020 Alexis Griffin.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
//  Created by Alex Griffin on 21/08/2020.
//


//A contiguous buffer allocated on the heap containing elements of a particular type.
internal class ContiguousMutableBuffer<T> where T: BufferElement
{
    private let blueprint: T = T();
    private let buffer: UnsafeMutablePointer<T?>;
    
    private let initialCapacity: Int;
    private var capacity: Int;
    private var count: Int = 0;
    
    public init(withInitialCapacity: Int)
    {
        //Set the initial capacity
        initialCapacity = withInitialCapacity;
        capacity = initialCapacity;
        
        // populate the buffer, fill with nil
        buffer = UnsafeMutablePointer<T?>.allocate(capacity: initialCapacity);
        buffer.initialize(repeating: nil, count: initialCapacity);
    }
    
    public func ItemAt(_ index: Int) throws -> T
    {
        if (index < count)
        {
            return buffer[index]!;
        }
        
        throw ContiguousMutableBufferError.OutOfRange;
    }
    
    public func AddNew()
    {
        self.Add(blueprint);
    }
    
    public func Add(_ element: T)
    {
        let p: UnsafeMutablePointer<T?> = buffer.advanced(by: count);
        p.initialize(to: element);
        
        count += 1;
    }
    
    //Insert 'insert' function here. 
    
    public func Delete(_ index: Int) throws
    {
        if (index < count)
        {
            if (index == (count - 1) )
            {
                buffer[index] = nil;
                count -= 1;
            }
            else
            {
                let p: UnsafeMutablePointer<T?> = buffer.advanced(by: index);
                    
                p.assign(from: buffer.advanced(by: index + 1),count: count - index );
                buffer[count - 1] = nil;
                count -= 1;
            }
        }
        
        throw ContiguousMutableBufferError.OutOfRange;
    }
    
    deinit
    {
        buffer.deallocate();
    }
}

internal enum ContiguousMutableBufferError: Error
{
    case OutOfRange;
}
