/*
Copyright © 2020 Alexis Griffin.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
//  Created by Alex Griffin on 11/2/20.
//


/*
 A RenderQueue represents an array of batched items that will be drawn on a particular frame. It's basically a frame buffer of sorts.
 Platforms are supposed to implement the platform specific approach so as to push the information to the renderer as quickly as possible.
 There are (usually) three RenderQueues in our render pipeline.
*/

public protocol RenderQueue
{
    var QueuePointer: UnsafeMutableRawPointer { get };

    func IsClear() -> Bool;
    
    func BatchBufferSize() -> Int;
    func BatchBufferCount() -> Int;
    func ItemBufferSize() -> Int;
    func ItemBufferCount() -> Int;
    
    init();
    func PushBatch(_ texture: Texture) -> Int;
    
    func CanFitItems(_ itemCount: Int) -> Bool;
    func GrowItemBuffer(_ itemCount: Int);
    func CanFitBatches(_ batchCount: Int) -> Bool;
    func GrowBatchBuffer(_ batchCount: Int);

    //Returns batch relative position of item.
    func PushItemToRenderBatch(batchPosition: Int, itemPosition: Vec2, texturePosition: Vec2) -> Int;
    func GetBatchItemCount(_ batchPosition: Int) -> Int;
}

public protocol RenderBatch
{
    
}
