/*
Copyright © 2020 Alexis Griffin.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
//  Created by Alex Griffin on 14/1/20.
//

public struct Size
{
    public let Width: Float;
    public let Height: Float;
    
    public init(_ width: Float, _ height: Float)
    {
        Width = width;
        Height = height;
    }
}

public struct Quad
{
    public let TL: Vec2;
    public let TR: Vec2;
    public let BL: Vec2;
    public let BR: Vec2;
    
    public init(tl: Vec2, tr: Vec2, bl: Vec2, br: Vec2)
    {
        self.TL = tl;
        self.TR = tr;
        self.BL = bl;
        self.BR = br;
    }
    
    public init(_ rect: Rect)
    {
        self.TL = rect.Position;
        self.TR = Vec2(rect.x + rect.width, rect.y);
        self.BL = Vec2(rect.x, rect.y + rect.height);
        self.BR = Vec2(rect.x + rect.width, rect.y + rect.height);
    }
}

public struct Rect
{
    public let Position: Vec2; //Top Left
    public let Size: Size; //Bottom Right
    
    @inline (__always) public var x: Float { get { return Position.x; } }
    @inline (__always) public var y: Float { get { return Position.y; } }
    @inline (__always) public var width: Float { get { return Size.Width; } }
    @inline (__always) public var height: Float { get { return Size.Height; } }
    
    public init (_ position: Vec2, _ size: Size)
    {
        Position = position;
        Size = size;
    }
}

