/*
Copyright © 2020 Alexis Griffin.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
//
//  Trig.swift
//  Meant to wrap around the different ways of importing Math.h in Swift.
//  WIP as I need the various functions.
//
//  Created by Alex Griffin on 30/12/19.
//

#if os(macOS) || os(iOS) //Darwin
import Darwin;

public func sin(_ angleInRad: Double) -> Double
{
    return Darwin.sin(angleInRad);
}

public func sinf(_ angleInRad: Float) -> Float
{
    return Darwin.sinf(angleInRad);
}

public func cos(_ angleInRad: Double) -> Double
{
    return Darwin.cos(angleInRad);
}

public func cosf(_ angleInRad: Float) -> Float
{
    return Darwin.cosf(angleInRad);
}

public func tan(_ angleInRad: Double) -> Double
{
    return Darwin.tan(angleInRad);
}

public func tanf(_ angleInRad: Float) -> Float
{
    return Darwin.tanf(angleInRad);
}

//Inverse trig
public func atan(_ angleInRad: Double) -> Double
{
    return Darwin.atan(angleInRad);
}

public func atanf(_ angleInRad: Float) -> Float
{
    return Darwin.atanf(angleInRad);
}

public func atan2(_ y: Double,_ x: Double) -> Double
{
    return Darwin.atan2(y,x);
}

public func atan2f(_ y: Float,_ x: Float) -> Float
{
    return Darwin.atan2f(y,x);
}

#endif
