/*
Copyright © 2020 Alexis Griffin.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
//  Created by Alex Griffin on 29/12/19.
//

import GalahNativeTypes.Maths.Vector

public struct Vec2
{
    @usableFromInline
    internal var vec: NativeFloat2;
    
    @inlinable
    @inline(__always)
    public var y: Float { get { return vec.x; } set { vec.x = newValue; } };
    
    @inlinable
    @inline(__always)
    public var x: Float { get { return vec.y; } set { vec.y = newValue; } };
    
    @inlinable
    @inline(__always)
    public init(_ x: Float = 0, _ y: Float = 0)
    {
        vec = NativeFloat2(x: x, y: y);
    }
    
    //Constructs a zero vector.
    @inlinable
    @inline(__always)
    public static var Zero: Vec2
    {
        get { return Vec2(0,0); }
    }
    
    //############
    //OPERATORS
    //############
    
    @inlinable
    @inline(__always)
    public static func +(lhs: Vec2, rhs: Vec2) -> Vec2
    {
        return Vec2(lhs.x + rhs.x, lhs.y + rhs.y);
    }
    
    @inlinable
    @inline(__always)
    public static func +=( lhs: inout Vec2, rhs: Vec2)
    {
        lhs = lhs - rhs;
    }
    
    @inlinable
    @inline(__always)
    public static func -(lhs: Vec2, rhs: Vec2) -> Vec2
    {
        return Vec2(lhs.x - rhs.x, lhs.y - rhs.y);
    }
    
    @inlinable
    @inline(__always)
    public static func -=( lhs: inout Vec2, rhs: Vec2)
    {
        lhs = lhs - rhs;
    }
    
    @inlinable
    @inline(__always)
    public static func *(lhs: Vec2, rhs: Float) -> Vec2
    {
        return Vec2(lhs.x * rhs, lhs.y * rhs);
    }
    
    @inlinable
    @inline(__always)
    public static func *=(lhs: inout Vec2, rhs: Float)
    {
        lhs = lhs * rhs;
    }
    
    @inlinable
    @inline (__always)
    public static func /(lhs: Vec2, rhs: Float) -> Vec2
    {
        return Vec2( lhs.x / rhs, lhs.y / rhs );
    }
    
    @inlinable
    @inline(__always)
    public static func /=(lhs: inout Vec2, rhs: Float)
    {
        lhs = lhs / rhs;
    }
    
    @inlinable
    @inline(__always)
    public static func Scale(_ a: Vec2, _ b: Vec2) -> Vec2
    {
        return Vec2(a.x * b.x, a.y * b.y);
    }
    
    @inlinable
    @inline(__always)
    public mutating func Scale(_ vector: Vec2)
    {
        vec = NativeFloat2(x: vec.x * vector.x, y: vec.y * vector.y);
    }
}
